name: Employeefrontend DevSecOps Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Build Step 1
        run: echo "Build Step 1"

      - name: Build Step 2
        run: echo "Build Step 2"

  test-job: 
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test Step 1
        run: echo "test Step 1"
        
      - name: test Step 2
        run: echo "test Step 2"

  provision-job: 
    runs-on: ubuntu-latest
    steps:
      - name: provision Step 1
        run: echo "provision Step 1"
        
      - name: provision Step 2
        run: echo "provision Step 2"

  deploy-job: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy Step 1
        run: echo "deploy Step 1"
              
      - name: deploy Step 2
        run: echo "deploy Step 2"

  monitor-job: 
    runs-on: ubuntu-latest
    steps:
      - name: monitor Step 1
        run: echo "monitor Step 1"
                    
      - name: monitor Step 2
        run: echo "monitor Step 2"



